name: GitHub Pages Push
on:
  push:
    branches:
      - master
jobs:

  gh-pages-push:
    runs-on: ubuntu-latest
    steps:
    
      - run: echo "${{ github.workflow }} workflow triggered by ${{ github.event_name }} ${{ github.sha }} on ${{ github.repository }}:${{ github.ref }}"
      - run: echo "Job ${{ github.action }} now running on ${{ runner.os }}"
      
      - run: echo "Checking out ${{ github.repository }}"
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "${{ github.repository }} has been cloned to the runner."

      - run: echo "Setting up Node environment"
      - uses: actions/setup-node@v2
      - run: npm install
      - run: echo "Node environment setup and dependencies installed"
      - run: echo "Starting build"
      - run: npm run build
      - run: echo "Build completed"
      
      - run: echo "Pushing dist folder to ${{ github.repository }}:gh-pages"
      - run: git config --global user.name "GitHub Actions"
      - run: git config --global user.email "actions@github.com.com"
      - run: git add dist -f
      - run: git commit -m "forcing dist commit"
      - run: git subtree split --prefix dist -b gh-pages
      - run: git push -f origin gh-pages:gh-pages
      - run: echo "Push complete"

      - run: echo "This job's status is ${{ job.status }}."